version: '3'

services:
  app:
    build: ./front/
    command: yarn serve -s ./build -l 3000
    ports:
      - "80:3000"
  
  server:
    build: ./back/
    command: yarn start
    ports:
      - "3003:3003"
  
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "justapassword"
      POSTGRES_USER: "admin"